# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_myabstractmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('myabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.MyAbstractModel')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
            ],
            bases=('core.myabstractmodel',),
        ),
    ]
